/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.SDIDE.vista.gui;

import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.desarrollo.SDIDE.vista.util.ScrollDesktop;

/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {

	private JDesktopPane desktoppanel;

	/**
	 * Creates new form Login
	 */
	public Login() {
		desktoppanel = new JDesktopPane();
		initComponents();
		this.setLocationRelativeTo(this);
		this.setResizable(false);
		this.setName("Ventana de Ingreso");

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTFLoginUsuario = new javax.swing.JTextField();
		jLLoginPassword = new javax.swing.JLabel();
		jLLoginUsuario = new javax.swing.JLabel();
		jBLoginEntrar = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jPLoginColor = new javax.swing.JPanel();
		jLoginSistemasDeInformacionDeEgresados = new javax.swing.JLabel();
		ImgLoginLogo = new javax.swing.JLabel();
		jLoginSistemasDeInformacionDeEgresados1 = new javax.swing.JLabel();
		jLLoginTipoUsuario = new javax.swing.JLabel();
		jCBLoginTipoUsuario = new javax.swing.JComboBox();

		setBackground(new java.awt.Color(255, 255, 255));
		setForeground(java.awt.Color.white);

		jTFLoginUsuario.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

		jLLoginPassword.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
		jLLoginPassword.setText("Password:");

		jLLoginUsuario.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
		jLLoginUsuario.setText("Usuario:");

		jBLoginEntrar.setBackground(new java.awt.Color(102, 204, 255));
		jBLoginEntrar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
		jBLoginEntrar.setText("Entrar");
		jBLoginEntrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBLoginEntrarActionPerformed(evt);
			}
		});

		jPLoginColor.setBackground(new java.awt.Color(0, 0, 51));

		jLoginSistemasDeInformacionDeEgresados.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
		jLoginSistemasDeInformacionDeEgresados.setForeground(new java.awt.Color(255, 255, 255));
		jLoginSistemasDeInformacionDeEgresados.setText("Sistema De Información ");

		ImgLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_eam_mini.png"))); // NOI18N

		jLoginSistemasDeInformacionDeEgresados1.setFont(new java.awt.Font("Meiryo", 1, 18)); // NOI18N
		jLoginSistemasDeInformacionDeEgresados1.setForeground(new java.awt.Color(255, 255, 255));
		jLoginSistemasDeInformacionDeEgresados1.setText("De Egresados");

		javax.swing.GroupLayout jPLoginColorLayout = new javax.swing.GroupLayout(jPLoginColor);
		jPLoginColor.setLayout(jPLoginColorLayout);
		jPLoginColorLayout.setHorizontalGroup(jPLoginColorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginColorLayout.createSequentialGroup()
						.addGroup(jPLoginColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPLoginColorLayout.createSequentialGroup().addGap(19, 19, 19)
										.addComponent(jLoginSistemasDeInformacionDeEgresados,
												javax.swing.GroupLayout.PREFERRED_SIZE, 247,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPLoginColorLayout.createSequentialGroup()
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jLoginSistemasDeInformacionDeEgresados1,
														javax.swing.GroupLayout.PREFERRED_SIZE, 146,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(51, 51, 51)))
						.addComponent(ImgLoginLogo).addGap(33, 33, 33)));
		jPLoginColorLayout.setVerticalGroup(jPLoginColorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPLoginColorLayout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPLoginColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(ImgLoginLogo)
								.addGroup(jPLoginColorLayout.createSequentialGroup()
										.addComponent(jLoginSistemasDeInformacionDeEgresados,
												javax.swing.GroupLayout.PREFERRED_SIZE, 23,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLoginSistemasDeInformacionDeEgresados1,
												javax.swing.GroupLayout.PREFERRED_SIZE, 20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(13, 13, 13)))
						.addContainerGap()));

		jLLoginTipoUsuario.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
		jLLoginTipoUsuario.setText("Tipo de Usuario:");

		jCBLoginTipoUsuario.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
		jCBLoginTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Tipo de Usuario",
				"Contacto de la Empresa", "Egresado", "Personal de la EAM" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPLoginColor, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.PREFERRED_SIZE, 378, Short.MAX_VALUE)
				.addGroup(layout.createSequentialGroup().addGap(43, 43, 43)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup().addComponent(jLLoginTipoUsuario)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jCBLoginTipoUsuario,
												javax.swing.GroupLayout.PREFERRED_SIZE, 182,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addComponent(jBLoginEntrar)
								.addGroup(layout
										.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLLoginPassword).addComponent(jLLoginUsuario))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jPasswordField1).addComponent(jTFLoginUsuario,
														javax.swing.GroupLayout.PREFERRED_SIZE, 182,
														javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addComponent(jPLoginColor, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(32, 32, 32)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLLoginTipoUsuario).addComponent(jCBLoginTipoUsuario,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLLoginUsuario).addComponent(jTFLoginUsuario,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLLoginPassword))
						.addGap(18, 18, 18).addComponent(jBLoginEntrar).addGap(22, 22, 22)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jBLoginEntrarActionPerformed(java.awt.event.ActionEvent evt) {
		int emp = jCBLoginTipoUsuario.getSelectedIndex();
		if (emp == 1) {
			VentanaContactoEmpresa ven = new VentanaContactoEmpresa();
			ven.setVisible(true);
			this.setVisible(false);
		} else if (emp == 2) {
			VentanaEgresados ven2 = new VentanaEgresados();
			ven2.setVisible(true);
			this.setVisible(false);
		} else if (emp == 3) {
			VentanaPersonalEAM ven3 = new VentanaPersonalEAM();
			ven3.setVisible(true);
			this.setVisible(false);
		} else {
			JOptionPane.showMessageDialog(null, "Selecciona un tipo de Usuario");
		}

	}

	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel ImgLoginLogo;
	private javax.swing.JButton jBLoginEntrar;
	private javax.swing.JComboBox<String> jCBLoginTipoUsuario;
	private javax.swing.JLabel jLLoginPassword;
	private javax.swing.JLabel jLLoginTipoUsuario;
	private javax.swing.JLabel jLLoginUsuario;
	private javax.swing.JLabel jLoginSistemasDeInformacionDeEgresados;
	private javax.swing.JLabel jLoginSistemasDeInformacionDeEgresados1;
	private javax.swing.JPanel jPLoginColor;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTFLoginUsuario;
	// End of variables declaration//GEN-END:variables
}
