/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.SDIDE.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.AreaInteres;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Ciudad;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Departamento;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Egresado;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Facultad;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.InfoAcademica;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.InfoLaboral;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Pais;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Programa;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.SectorLaboral;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.enumeraciones.NivelAcademico;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.enumeraciones.SitucionLaboral;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.enumeraciones.TipoDocumento;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.enumeraciones.TipoEmpresa;
import co.edu.eam.ingesoft.desarrollo.SDIDE.vista.controlador.ControladorAdminEgresado;

/**
 *
 * @author user
 */
public class VentanaEgresados extends javax.swing.JFrame {

	/**
	 * Creates new form VentanaEgresados
	 */
	private ControladorAdminEgresado controlador;
	
	public VentanaEgresados() {
		initComponents();
		setVisible(true);
		setResizable(false);
		this.setLocationRelativeTo(this);
		this.setResizable(false);
		this.setName("Ventana de Egresado");
		controlador = new ControladorAdminEgresado();
		jCBEgrRegEgrTipoDocumento.addItem("Seleccione un tipo");
		jCBEgrRegEgrTipoDocumento.addItem(TipoDocumento.Cedula);
		jCBEgrRegEgrTipoDocumento.addItem(TipoDocumento.TI);
		jCBEgrInfAcaNivelAcademicoPrograma.addItem("Seleccione un nivel");
        jCBEgrInfAcaNivelAcademicoPrograma.addItem(NivelAcademico.Postgrado);
        jCBEgrInfAcaNivelAcademicoPrograma.addItem(NivelAcademico.Pregrado);
        jCBEgrInfAcaNivelAcademicoPrograma.addItem(NivelAcademico.Diplomado);
        jCBEgrInfLabSituacionActual.addItem("Seleccione Situacion");
        jCBEgrInfLabSituacionActual.addItem(SitucionLaboral.Empleado);
        jCBEgrInfLabSituacionActual.addItem(SitucionLaboral.Desempleado);
        jCBEgrInfLabSituacionActual.addItem(SitucionLaboral.Empresario);
        jCBEgrInfLabSituacionActual.addItem(SitucionLaboral.Independiante);
        jCBEgrInfLabTipoEmpresa.addItem("Seleccione Tipo");
        jCBEgrInfLabTipoEmpresa.addItem(TipoEmpresa.Privada);
        jCBEgrInfLabTipoEmpresa.addItem(TipoEmpresa.Publica);
        
        cargarFacultades();
        cargarEmpresas();
       
	}

	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPrincipalE = new javax.swing.JPanel();
        jTPEgrPestaniasPrincipales = new javax.swing.JTabbedPane();
        jPEgrInfEmpresas = new javax.swing.JPanel();
        jTPEgrPestaniasInfEgresados = new javax.swing.JTabbedPane();
        jPEgrRegistroEgresados = new javax.swing.JPanel();
        jBEgrRegEgrSiguiente = new javax.swing.JButton();
        jTFEgrRegEgrNumeroTelCel = new javax.swing.JTextField();
        jTFEgrRegEgrNumeroDocumento = new javax.swing.JTextField();
        jCBEgrRegEgrTipoDocumento = new javax.swing.JComboBox();
        jLEgrRegEgrTipoDocumento = new javax.swing.JLabel();
        jLEgrRegEgrNumeroDocumento = new javax.swing.JLabel();
        jLEgrRegEgrNumeroTelCel = new javax.swing.JLabel();
        jTFEgrRegEgrCorreo = new javax.swing.JTextField();
        jTFEgrRegEgrSegundoApellido = new javax.swing.JTextField();
        jTFEgrRegEgrPrimerApellido = new javax.swing.JTextField();
        jTFEgrRegEgrNombres = new javax.swing.JTextField();
        jLEgrRegEgrNombres = new javax.swing.JLabel();
        jLEgrRegEgrPrimerApellido = new javax.swing.JLabel();
        jLEgrRegEgrSegundoApellido = new javax.swing.JLabel();
        jLEgrRegEgrCorreo = new javax.swing.JLabel();
        jPEgrInfAcademica = new javax.swing.JPanel();
        jTFEgrInfAcaNumeroDiploma = new javax.swing.JTextField();
        jLEgrInfAcaNumeroDiploma = new javax.swing.JLabel();
        jLEgrInfAcaFacultad = new javax.swing.JLabel();
        jCBEgrInfAcaFacultad = new javax.swing.JComboBox();
        jCBEgrInfAcaProgramaAcademico = new javax.swing.JComboBox();
        jLEgrInfAcaProgramaAcademico = new javax.swing.JLabel();
        jLEgrInfAcaFechaGrado = new javax.swing.JLabel();
        jLEgrInfAcaNivelAcademicoPrograma = new javax.swing.JLabel();
        jCBEgrInfAcaNivelAcademicoPrograma = new javax.swing.JComboBox();
        jLEgrInfAcaAreasConocimientoAplicar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEgrInfAcaAreasConocimientoAplicar = new javax.swing.JTextArea();
        jBEgrInfAcaAtras = new javax.swing.JButton();
        jBEgrInfAcaAreasSiguiente = new javax.swing.JButton();
        jDCEgrInfAcaFechaGrado = new com.toedter.calendar.JDateChooser();
        jPEgrInfLaboral = new javax.swing.JPanel();
        jCBEgrInfLabSituacionActual = new javax.swing.JComboBox();
        jLEgrInfLabSituacionActual = new javax.swing.JLabel();
        jLEgrInfLabTipoEmpresa = new javax.swing.JLabel();
        jCBEgrInfLabTipoEmpresa = new javax.swing.JComboBox();
        jTFEgrInfLabSectorLaboral = new javax.swing.JTextField();
        jLEgrInfLabSectorLaboral = new javax.swing.JLabel();
        jLEgrInfLabNombreEmpresa = new javax.swing.JLabel();
        jTFEgrInfLabNombreEmpresa = new javax.swing.JTextField();
        jLEgrInfLabFechaIngreso = new javax.swing.JLabel();
        jLEgrInfLabFechaSalida = new javax.swing.JLabel();
        jTFLEgrInfLabCargoDentroEmpresa = new javax.swing.JTextField();
        jLEgrInfLabCargoDentroEmpresa = new javax.swing.JLabel();
        jBEgrInfLabRegistrar = new javax.swing.JButton();
        jBEgrInfLabAtras = new javax.swing.JButton();
        jDCEgrInfLabFechaIngreso = new com.toedter.calendar.JDateChooser();
        jDCEgrInfLabFechaSalida = new com.toedter.calendar.JDateChooser();
        jBEgrEdiInfLAbCargarInfLabEditar = new javax.swing.JButton();
        jPEgrEditarEgresados = new javax.swing.JPanel();
        jBEgrEdiInfEgrCargarInfPerEditar = new javax.swing.JButton();
        jTFEgrEdiInfEgrNumeroDocumento = new javax.swing.JTextField();
        jLEgrEdiInfEgrNumeroDocumento = new javax.swing.JLabel();
        jPEgrBolsaEmpleo = new javax.swing.JPanel();
        jTPEgrPestaniasBolsaDeEmpleo = new javax.swing.JTabbedPane();
        jPEgrVerOfertaInteres = new javax.swing.JPanel();
        jLEgrVerOfertasInteresOfertas = new javax.swing.JLabel();
        jLEgrVerOfertasInteresAreaInteres = new javax.swing.JLabel();
        jCBEgrVerOfertasInteresAreaInteres = new javax.swing.JComboBox();
        jBEgrVerOfertasInteresActualizar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTAEgrVerOfertasInteresActualizar = new javax.swing.JTextArea();
        jBEgrVerOfeAplicar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLEgrSistemaDeInformacionDeEgresados = new javax.swing.JLabel();
        jLEgrSistemaDeInformacionDeEgresados1 = new javax.swing.JLabel();
        ImgLoginLogo = new javax.swing.JLabel();
        jBCerrarSesionEgre = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPPrincipalE.setBackground(new java.awt.Color(255, 255, 255));

        jTPEgrPestaniasPrincipales.setBackground(new java.awt.Color(0, 0, 51));
        jTPEgrPestaniasPrincipales.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N

        jPEgrInfEmpresas.setBackground(new java.awt.Color(255, 255, 255));

        jTPEgrPestaniasInfEgresados.setBackground(new java.awt.Color(0, 0, 51));
        jTPEgrPestaniasInfEgresados.setFont(new java.awt.Font("Meiryo", 2, 11)); // NOI18N

        jPEgrRegistroEgresados.setBackground(new java.awt.Color(255, 255, 255));

        jBEgrRegEgrSiguiente.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrRegEgrSiguiente.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrRegEgrSiguiente.setText("Siguiente");
        jBEgrRegEgrSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrRegEgrSiguienteActionPerformed(evt);
            }
        });

        jTFEgrRegEgrNumeroTelCel.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jTFEgrRegEgrNumeroDocumento.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jCBEgrRegEgrTipoDocumento.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrRegEgrTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Tipo de Documento", "Cedula de ciudadania", "Tarjeta de Identidad" }));

        jLEgrRegEgrTipoDocumento.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrTipoDocumento.setText("Tipo de Documento:");

        jLEgrRegEgrNumeroDocumento.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrNumeroDocumento.setText("Numero del Documento:");

        jLEgrRegEgrNumeroTelCel.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrNumeroTelCel.setText("Numero Telefono/Celular:");

        jTFEgrRegEgrCorreo.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jTFEgrRegEgrSegundoApellido.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jTFEgrRegEgrPrimerApellido.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jTFEgrRegEgrNombres.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEgrRegEgrNombres.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrNombres.setText("Nombre(s):");

        jLEgrRegEgrPrimerApellido.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrPrimerApellido.setText("Primer Apellido:");

        jLEgrRegEgrSegundoApellido.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrSegundoApellido.setText("Segundo Apellido:");

        jLEgrRegEgrCorreo.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrRegEgrCorreo.setText("Correo Electronico:");

        javax.swing.GroupLayout jPEgrRegistroEgresadosLayout = new javax.swing.GroupLayout(jPEgrRegistroEgresados);
        jPEgrRegistroEgresados.setLayout(jPEgrRegistroEgresadosLayout);
        jPEgrRegistroEgresadosLayout.setHorizontalGroup(
            jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrRegistroEgresadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEgrRegistroEgresadosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLEgrRegEgrPrimerApellido))
                    .addComponent(jLEgrRegEgrNombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLEgrRegEgrSegundoApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLEgrRegEgrCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEgrRegEgrNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEgrRegEgrPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEgrRegEgrSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEgrRegEgrCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLEgrRegEgrTipoDocumento)
                    .addComponent(jLEgrRegEgrNumeroDocumento)
                    .addComponent(jLEgrRegEgrNumeroTelCel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCBEgrRegEgrTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFEgrRegEgrNumeroDocumento)
                    .addComponent(jTFEgrRegEgrNumeroTelCel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEgrRegistroEgresadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBEgrRegEgrSiguiente)
                .addGap(29, 29, 29))
        );
        jPEgrRegistroEgresadosLayout.setVerticalGroup(
            jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrRegistroEgresadosLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEgrRegEgrNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEgrRegEgrNombres)
                    .addComponent(jLEgrRegEgrTipoDocumento)
                    .addComponent(jCBEgrRegEgrTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEgrRegEgrPrimerApellido)
                    .addComponent(jTFEgrRegEgrPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEgrRegEgrNumeroDocumento)
                    .addComponent(jTFEgrRegEgrNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEgrRegEgrSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEgrRegEgrSegundoApellido)
                    .addComponent(jLEgrRegEgrNumeroTelCel)
                    .addComponent(jTFEgrRegEgrNumeroTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEgrRegistroEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFEgrRegEgrCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEgrRegEgrCorreo))
                .addGap(37, 37, 37)
                .addComponent(jBEgrRegEgrSiguiente)
                .addGap(43, 43, 43))
        );

        jTPEgrPestaniasInfEgresados.addTab("Registrar Egresado", jPEgrRegistroEgresados);

        jPEgrInfAcademica.setBackground(new java.awt.Color(255, 255, 255));

        jTFEgrInfAcaNumeroDiploma.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEgrInfAcaNumeroDiploma.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfAcaNumeroDiploma.setText("Número del Diploma:");

        jLEgrInfAcaFacultad.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfAcaFacultad.setText("Facultad:");

        jCBEgrInfAcaFacultad.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrInfAcaFacultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Facultad" }));

        jCBEgrInfAcaProgramaAcademico.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrInfAcaProgramaAcademico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Programa Académico", " " }));

        jLEgrInfAcaProgramaAcademico.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfAcaProgramaAcademico.setText("Programa Académico:");

        jLEgrInfAcaFechaGrado.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfAcaFechaGrado.setText("Fecha de Grado:");

        jLEgrInfAcaNivelAcademicoPrograma.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfAcaNivelAcademicoPrograma.setText("Nivel Académico del Programa:");

        jCBEgrInfAcaNivelAcademicoPrograma.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrInfAcaNivelAcademicoPrograma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Nivel Académico", "Diplomado", "Pregrado", "Postgrado", " " }));

        jLEgrInfAcaAreasConocimientoAplicar.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfAcaAreasConocimientoAplicar.setText("Áreas de conocimiento a las cuales le interesaría aplicar:");

        jTAEgrInfAcaAreasConocimientoAplicar.setColumns(20);
        jTAEgrInfAcaAreasConocimientoAplicar.setFont(new java.awt.Font("Meiryo", 0, 12)); // NOI18N
        jTAEgrInfAcaAreasConocimientoAplicar.setRows(5);
        jScrollPane1.setViewportView(jTAEgrInfAcaAreasConocimientoAplicar);

        jBEgrInfAcaAtras.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrInfAcaAtras.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrInfAcaAtras.setText("Atras");
        jBEgrInfAcaAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrInfAcaAtrasActionPerformed(evt);
            }
        });

        jBEgrInfAcaAreasSiguiente.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrInfAcaAreasSiguiente.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrInfAcaAreasSiguiente.setText("Siguiente");
        jBEgrInfAcaAreasSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrInfAcaAreasSiguienteActionPerformed(evt);
            }

			private void jBEgrInfAcaAreasSiguienteActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				
			}
        });

        javax.swing.GroupLayout jPEgrInfAcademicaLayout = new javax.swing.GroupLayout(jPEgrInfAcademica);
        jPEgrInfAcademica.setLayout(jPEgrInfAcademicaLayout);
        jPEgrInfAcademicaLayout.setHorizontalGroup(
            jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLEgrInfAcaNumeroDiploma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEgrInfAcaNumeroDiploma))
                    .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                                    .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLEgrInfAcaFechaGrado)
                                        .addComponent(jLEgrInfAcaProgramaAcademico)
                                        .addComponent(jLEgrInfAcaFacultad))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jCBEgrInfAcaFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCBEgrInfAcaProgramaAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jDCEgrInfAcaFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                                    .addComponent(jLEgrInfAcaNivelAcademicoPrograma)
                                    .addGap(10, 10, 10)
                                    .addComponent(jCBEgrInfAcaNivelAcademicoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jBEgrInfAcaAtras))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEgrInfAcademicaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEgrInfAcaAreasConocimientoAplicar)
                        .addGap(37, 37, 37))
                    .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEgrInfAcaAreasSiguiente))
                        .addGap(61, 61, 61))))
        );
        jPEgrInfAcademicaLayout.setVerticalGroup(
            jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEgrInfAcaFacultad)
                    .addComponent(jCBEgrInfAcaFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEgrInfAcaAreasConocimientoAplicar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEgrInfAcademicaLayout.createSequentialGroup()
                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEgrInfAcaProgramaAcademico)
                            .addComponent(jCBEgrInfAcaProgramaAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEgrInfAcaFechaGrado)
                            .addComponent(jDCEgrInfAcaFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEgrInfAcaNivelAcademicoPrograma)
                            .addComponent(jCBEgrInfAcaNivelAcademicoPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEgrInfAcaNumeroDiploma)
                            .addComponent(jTFEgrInfAcaNumeroDiploma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(jPEgrInfAcademicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEgrInfAcaAtras)
                    .addComponent(jBEgrInfAcaAreasSiguiente))
                .addGap(26, 26, 26))
        );

        jTPEgrPestaniasInfEgresados.addTab("Información Académica", jPEgrInfAcademica);

        jPEgrInfLaboral.setBackground(new java.awt.Color(255, 255, 255));
        jPEgrInfLaboral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCBEgrInfLabSituacionActual.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrInfLabSituacionActual.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione su Situación", "Desempleado", "Empleado", "Independiente", "Empresario" }));
        jPEgrInfLaboral.add(jCBEgrInfLabSituacionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 23, 190, -1));

        jLEgrInfLabSituacionActual.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabSituacionActual.setText("Situación Actual:");
        jPEgrInfLaboral.add(jLEgrInfLabSituacionActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 25, -1, -1));

        jLEgrInfLabTipoEmpresa.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabTipoEmpresa.setText("Tipo de Empresa:");
        jPEgrInfLaboral.add(jLEgrInfLabTipoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 53, -1, -1));

        jCBEgrInfLabTipoEmpresa.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrInfLabTipoEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Tipo de Empresa", "Pública ", "Privada" }));
        jPEgrInfLaboral.add(jCBEgrInfLabTipoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 51, 190, -1));

        jTFEgrInfLabSectorLaboral.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N
        jPEgrInfLaboral.add(jTFEgrInfLabSectorLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 84, 190, -1));

        jLEgrInfLabSectorLaboral.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabSectorLaboral.setText("Sector Laboral:");
        jPEgrInfLaboral.add(jLEgrInfLabSectorLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 87, -1, -1));

        jLEgrInfLabNombreEmpresa.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabNombreEmpresa.setText("Nombre de la Empresa:");
        jPEgrInfLaboral.add(jLEgrInfLabNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 26, -1, -1));

        jTFEgrInfLabNombreEmpresa.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N
        jPEgrInfLaboral.add(jTFEgrInfLabNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 23, 182, -1));

        jLEgrInfLabFechaIngreso.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabFechaIngreso.setText("Fecha de Ingreso:");
        jPEgrInfLaboral.add(jLEgrInfLabFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 52, -1, -1));

        jLEgrInfLabFechaSalida.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabFechaSalida.setText("Fecha de Salida:");
        jPEgrInfLaboral.add(jLEgrInfLabFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 78, -1, -1));

        jTFLEgrInfLabCargoDentroEmpresa.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N
        jPEgrInfLaboral.add(jTFLEgrInfLabCargoDentroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 104, 182, -1));

        jLEgrInfLabCargoDentroEmpresa.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrInfLabCargoDentroEmpresa.setText("Cargo Dentro de la Empresa:");
        jPEgrInfLaboral.add(jLEgrInfLabCargoDentroEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 107, -1, -1));

        jBEgrInfLabRegistrar.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrInfLabRegistrar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrInfLabRegistrar.setText("Registar");
        jBEgrInfLabRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrInfLabRegistrarActionPerformed(evt);
            }
        });
        jPEgrInfLaboral.add(jBEgrInfLabRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(675, 202, -1, -1));

        jBEgrInfLabAtras.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrInfLabAtras.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrInfLabAtras.setText("Atras");
        jBEgrInfLabAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrInfLabAtrasActionPerformed(evt);
            }
        });
        jPEgrInfLaboral.add(jBEgrInfLabAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 202, -1, -1));
        jPEgrInfLaboral.add(jDCEgrInfLabFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 52, 183, -1));
        jPEgrInfLaboral.add(jDCEgrInfLabFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 78, 183, -1));

        jBEgrEdiInfLAbCargarInfLabEditar.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrEdiInfLAbCargarInfLabEditar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrEdiInfLAbCargarInfLabEditar.setText("Editar");
        jBEgrEdiInfLAbCargarInfLabEditar.setEnabled(false);
        jBEgrEdiInfLAbCargarInfLabEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrEdiInfLAbCargarInfLabEditarActionPerformed(evt);
            }
        });
        jPEgrInfLaboral.add(jBEgrEdiInfLAbCargarInfLabEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, -1, -1));

        jTPEgrPestaniasInfEgresados.addTab("Información Laboral", jPEgrInfLaboral);

        jPEgrEditarEgresados.setBackground(new java.awt.Color(255, 255, 255));

        jBEgrEdiInfEgrCargarInfPerEditar.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrEdiInfEgrCargarInfPerEditar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrEdiInfEgrCargarInfPerEditar.setText("Cargar Información Personal a Editar");
        jBEgrEdiInfEgrCargarInfPerEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrEdiInfEgrCargarInfPerEditarActionPerformed(evt);
            }
        });

        jTFEgrEdiInfEgrNumeroDocumento.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEgrEdiInfEgrNumeroDocumento.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrEdiInfEgrNumeroDocumento.setText("Numero del Documento:");

        javax.swing.GroupLayout jPEgrEditarEgresadosLayout = new javax.swing.GroupLayout(jPEgrEditarEgresados);
        jPEgrEditarEgresados.setLayout(jPEgrEditarEgresadosLayout);
        jPEgrEditarEgresadosLayout.setHorizontalGroup(
            jPEgrEditarEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrEditarEgresadosLayout.createSequentialGroup()
                .addGroup(jPEgrEditarEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEgrEditarEgresadosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLEgrEdiInfEgrNumeroDocumento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFEgrEdiInfEgrNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEgrEditarEgresadosLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jBEgrEdiInfEgrCargarInfPerEditar)))
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPEgrEditarEgresadosLayout.setVerticalGroup(
            jPEgrEditarEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrEditarEgresadosLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPEgrEditarEgresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEgrEdiInfEgrNumeroDocumento)
                    .addComponent(jTFEgrEdiInfEgrNumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jBEgrEdiInfEgrCargarInfPerEditar)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jTPEgrPestaniasInfEgresados.addTab("Editar Información de Egresado", jPEgrEditarEgresados);

        javax.swing.GroupLayout jPEgrInfEmpresasLayout = new javax.swing.GroupLayout(jPEgrInfEmpresas);
        jPEgrInfEmpresas.setLayout(jPEgrInfEmpresasLayout);
        jPEgrInfEmpresasLayout.setHorizontalGroup(
            jPEgrInfEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrInfEmpresasLayout.createSequentialGroup()
                .addComponent(jTPEgrPestaniasInfEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPEgrInfEmpresasLayout.setVerticalGroup(
            jPEgrInfEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEgrPestaniasInfEgresados)
        );

        jTPEgrPestaniasPrincipales.addTab("Información de los Egresados", jPEgrInfEmpresas);

        jPEgrBolsaEmpleo.setBackground(new java.awt.Color(255, 255, 255));

        jTPEgrPestaniasBolsaDeEmpleo.setBackground(new java.awt.Color(0, 0, 51));
        jTPEgrPestaniasBolsaDeEmpleo.setFont(new java.awt.Font("Meiryo", 2, 11)); // NOI18N

        jPEgrVerOfertaInteres.setBackground(new java.awt.Color(255, 255, 255));

        jLEgrVerOfertasInteresOfertas.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrVerOfertasInteresOfertas.setText("Ofertas:");

        jLEgrVerOfertasInteresAreaInteres.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEgrVerOfertasInteresAreaInteres.setText("Áreas de Interés :");

        jCBEgrVerOfertasInteresAreaInteres.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEgrVerOfertasInteresAreaInteres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Área" }));

        jBEgrVerOfertasInteresActualizar.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrVerOfertasInteresActualizar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrVerOfertasInteresActualizar.setText("Actualizar");
        jBEgrVerOfertasInteresActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrVerOfertasInteresActualizarActionPerformed(evt);
            }
        });

        jTAEgrVerOfertasInteresActualizar.setColumns(20);
        jTAEgrVerOfertasInteresActualizar.setRows(5);
        jScrollPane6.setViewportView(jTAEgrVerOfertasInteresActualizar);

        jBEgrVerOfeAplicar.setBackground(new java.awt.Color(102, 204, 255));
        jBEgrVerOfeAplicar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEgrVerOfeAplicar.setText("Aplicar");
        jBEgrVerOfeAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEgrVerOfeAplicarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEgrVerOfertaInteresLayout = new javax.swing.GroupLayout(jPEgrVerOfertaInteres);
        jPEgrVerOfertaInteres.setLayout(jPEgrVerOfertaInteresLayout);
        jPEgrVerOfertaInteresLayout.setHorizontalGroup(
            jPEgrVerOfertaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEgrVerOfertaInteresLayout.createSequentialGroup()
                .addGroup(jPEgrVerOfertaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEgrVerOfertaInteresLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLEgrVerOfertasInteresAreaInteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEgrVerOfertasInteresAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEgrVerOfertaInteresLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jBEgrVerOfertasInteresActualizar))
                    .addGroup(jPEgrVerOfertaInteresLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jBEgrVerOfeAplicar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPEgrVerOfertaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEgrVerOfertasInteresOfertas)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPEgrVerOfertaInteresLayout.setVerticalGroup(
            jPEgrVerOfertaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEgrVerOfertaInteresLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLEgrVerOfertasInteresOfertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEgrVerOfertaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEgrVerOfertaInteresLayout.createSequentialGroup()
                        .addGroup(jPEgrVerOfertaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEgrVerOfertasInteresAreaInteres)
                            .addComponent(jCBEgrVerOfertasInteresAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(jBEgrVerOfertasInteresActualizar)
                        .addGap(26, 26, 26)
                        .addComponent(jBEgrVerOfeAplicar))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTPEgrPestaniasBolsaDeEmpleo.addTab("Ver Ofertas de Interés", jPEgrVerOfertaInteres);

        javax.swing.GroupLayout jPEgrBolsaEmpleoLayout = new javax.swing.GroupLayout(jPEgrBolsaEmpleo);
        jPEgrBolsaEmpleo.setLayout(jPEgrBolsaEmpleoLayout);
        jPEgrBolsaEmpleoLayout.setHorizontalGroup(
            jPEgrBolsaEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEgrPestaniasBolsaDeEmpleo)
        );
        jPEgrBolsaEmpleoLayout.setVerticalGroup(
            jPEgrBolsaEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEgrPestaniasBolsaDeEmpleo)
        );

        jTPEgrPestaniasPrincipales.addTab("Bolsa de Empleo", jPEgrBolsaEmpleo);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLEgrSistemaDeInformacionDeEgresados.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLEgrSistemaDeInformacionDeEgresados.setForeground(new java.awt.Color(255, 255, 255));
        jLEgrSistemaDeInformacionDeEgresados.setText("Sistema De Información");

        jLEgrSistemaDeInformacionDeEgresados1.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLEgrSistemaDeInformacionDeEgresados1.setForeground(new java.awt.Color(255, 255, 255));
        jLEgrSistemaDeInformacionDeEgresados1.setText("De Egresados");

        ImgLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_eam.png"))); // NOI18N

        jBCerrarSesionEgre.setBackground(new java.awt.Color(0, 0, 51));
        jBCerrarSesionEgre.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBCerrarSesionEgre.setForeground(new java.awt.Color(153, 153, 153));
        jBCerrarSesionEgre.setText("Cerrar Sesion");
        jBCerrarSesionEgre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jBCerrarSesionEgre.setBorderPainted(false);
        jBCerrarSesionEgre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionEgreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLEgrSistemaDeInformacionDeEgresados1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCerrarSesionEgre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLEgrSistemaDeInformacionDeEgresados))
                .addGap(10, 10, 10)
                .addComponent(ImgLoginLogo))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLEgrSistemaDeInformacionDeEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEgrSistemaDeInformacionDeEgresados1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBCerrarSesionEgre)
                        .addContainerGap())))
            .addComponent(ImgLoginLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPPrincipalELayout = new javax.swing.GroupLayout(jPPrincipalE);
        jPPrincipalE.setLayout(jPPrincipalELayout);
        jPPrincipalELayout.setHorizontalGroup(
            jPPrincipalELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTPEgrPestaniasPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPPrincipalELayout.setVerticalGroup(
            jPPrincipalELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalELayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPEgrPestaniasPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPPrincipalE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	private void jBEgrInfAcaAreasSiguienteActionPerformed(ActionEvent evt) {
		jTPEgrPestaniasInfEgresados.setEnabledAt(2, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(2);
		
	}
   
	private void jBEgrRegEgrSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrRegEgrSiguienteActionPerformed
		jTPEgrPestaniasInfEgresados.setEnabledAt(1, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(1);

	}// GEN-LAST:event_jBEgrRegEgrSiguienteActionPerformed

	private void jBEgrInfAcaAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrInfAcaAtrasActionPerformed
		jTPEgrPestaniasInfEgresados.setEnabledAt(0, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(0);
	}// GEN-LAST:event_jBEgrInfAcaAtrasActionPerformed

	private void jBEgrInfAcaAreasRegistroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrInfAcaAreasRegistroActionPerformed
		jTPEgrPestaniasInfEgresados.setEnabledAt(2, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(2);
	}// GEN-LAST:event_jBEgrInfAcaAreasRegistroActionPerformed

	private void jBEgrInfLabAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrInfLabAtrasActionPerformed
		jTPEgrPestaniasInfEgresados.setEnabledAt(0, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(0);
	}// GEN-LAST:event_jBEgrInfLabAtrasActionPerformed

	private void jBEgrInfLabRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrInfLabRegistrarActionPerformed
		
		if (jTFEgrRegEgrNombres.getText().isEmpty() 
				|| jTFEgrRegEgrPrimerApellido.getText().isEmpty()
				|| jTFEgrRegEgrSegundoApellido.getText().isEmpty()
				|| jTFEgrRegEgrCorreo.getText().isEmpty()
				||jCBEgrRegEgrTipoDocumento.getSelectedIndex() == 0
				|| jTFEgrRegEgrNumeroDocumento.getText().isEmpty() 
				|| jTFEgrRegEgrNumeroTelCel.getText().isEmpty()
				|| jCBEgrInfAcaFacultad.getSelectedIndex() == 0
				|| jCBEgrInfAcaProgramaAcademico.getSelectedIndex() == 0
				|| jTAEgrInfAcaAreasConocimientoAplicar.getText().isEmpty()
				||jCBEgrInfAcaNivelAcademicoPrograma.getSelectedIndex() == 0
				||jTFEgrInfAcaNumeroDiploma.getText().isEmpty()
				||jCBEgrInfLabSituacionActual.getSelectedIndex() == 0
				||jCBEgrInfLabTipoEmpresa.getSelectedIndex() == 0
						||jTFEgrInfLabSectorLaboral.getText().isEmpty()
						||jTFEgrInfLabNombreEmpresa.getText().isEmpty()
						||jTFLEgrInfLabCargoDentroEmpresa.getText().isEmpty()
						
				) {
			JOptionPane.showMessageDialog(null, "Asegurese de ingresar todos los datos");
		} else {

			
			
		jTPEgrPestaniasInfEgresados.setEnabledAt(0, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(0);
		
		try {
			
			/* Informacion personal */
        	String nombre = jTFEgrRegEgrNombres.getText();
        	String apellido = jTFEgrRegEgrPrimerApellido.getText()+" "+jTFEgrRegEgrSegundoApellido.getText();
        	String correo = jTFEgrRegEgrCorreo.getText();
        	String telefono = jTFEgrRegEgrNumeroTelCel.getText();
        	TipoDocumento tipoDoc = (TipoDocumento) jCBEgrRegEgrTipoDocumento.getSelectedItem();
        	String numDocumento = jTFEgrRegEgrNumeroDocumento.getText();
        	
        	/* Informacion Academica */
        	Facultad facultad = (Facultad)jCBEgrInfAcaFacultad.getSelectedItem();
        	Programa programa = (Programa)jCBEgrInfAcaProgramaAcademico.getSelectedItem();
        	Date fechaGrado = jDCEgrInfAcaFechaGrado.getDate();
        	NivelAcademico nivelAcademico = (NivelAcademico)jCBEgrInfAcaNivelAcademicoPrograma.getSelectedItem();
        	String numeroDiploma= jTFEgrInfAcaNumeroDiploma.getText();
        	String areaConocimiento=jTAEgrInfAcaAreasConocimientoAplicar.getText();
        	
        	/* Informacion laboral */
        	String cargo = jTFLEgrInfLabCargoDentroEmpresa.getText();
        	Date fechaIngreso = jDCEgrInfLabFechaIngreso.getDate();
        	Date fechaSalida = jDCEgrInfLabFechaSalida.getDate();
        	SitucionLaboral situacionActual = (SitucionLaboral) jCBEgrInfLabSituacionActual.getSelectedItem();
        	Empresa empresa = (Empresa) jCBEgrInfLabTipoEmpresa.getSelectedItem();
        	
        	Egresado e = controlador.buscarEgresadoTipo(tipoDoc, numDocumento);
        	if(e != null ){
                JOptionPane.showMessageDialog(null, "Ya existe un egresado con el numero de identificacion "); 
        	}else{
        		int id = Integer.parseInt(numDocumento);
        		Egresado eg = controlador.buscarEgresado(id);
        		if(eg != null){
        			id = id+1;
        		}
        		
        		/*Informacion a egresado*/
        		Egresado egresado = new Egresado();
        		egresado.setIdEgresado(id);
        		egresado.setPrograma(programa);
        		egresado.setNombre(nombre);
        		egresado.setApellido(apellido);
        		egresado.setCorreo(correo);
        		egresado.setTelefono(telefono);
        		egresado.setTipoDoc(tipoDoc);
        		egresado.setNumDocumento(numDocumento);
        		
        		/*Informacion a Laboral*/
        		InfoLaboral infLaboral = new InfoLaboral();
        		infLaboral.setEgresado(egresado);
        		infLaboral.getIdEgresado();
        		infLaboral.setSitucionLaboral(situacionActual);
        		infLaboral.setFechaIngreso(fechaIngreso);
        		infLaboral.setFechaSalida(fechaSalida);
        		infLaboral.setCargoEmpresa(cargo);
        		
        		
        		/*Informacion a Academica*/
	        	InfoAcademica infAcademica = new InfoAcademica();
	        	infAcademica.setEgresado(egresado);
	        	infAcademica.setCodEgresado(egresado.getIdEgresado());
	        	infAcademica.setFechaGrado(fechaGrado);
	        	infAcademica.setFacultad(facultad);
	        	infAcademica.setProgramaAcademico(programa);
	        	infAcademica.setNivelAcademico(nivelAcademico);
	        	infAcademica.setNumeroDiploma(numeroDiploma);
	        	
	        	egresado.setInfoLaboral(infLaboral);
        		egresado.setInfoAcademica(infAcademica);
        		
        		//controlador.crearEgresado(egresado, Areas);
        				
        		}
		        JOptionPane.showMessageDialog(null, "Se ha registrado con exito "); 
		        
		
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		}
		
	}// GEN-LAST:event_jBEgrInfLabRegistrarActionPerformed

	private void jBEgrEdiInfEgrCargarInfPerEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrEdiInfEgrCargarInfPerEditarActionPerformed
		jTPEgrPestaniasInfEgresados.setEnabledAt(0, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(0);
		jBEgrInfAcaAreasSiguiente.setEnabled(false);
	}// GEN-LAST:event_jBEgrEdiInfEgrCargarInfPerEditarActionPerformed

	private void jBEgrEdiInfEgrEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrEdiInfEgrEditarActionPerformed
		
		jTPEgrPestaniasInfEgresados.setEnabledAt(2, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(2);
	}// GEN-LAST:event_jBEgrEdiInfEgrEditarActionPerformed

	private void jBEgrVerOfertasInteresActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrVerOfertasInteresActualizarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEgrVerOfertasInteresActualizarActionPerformed

	private void jBEgrVerOfeAplicarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrVerOfeAplicarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEgrVerOfeAplicarActionPerformed

	private void jBCerrarSesionEgreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCerrarSesionEgreActionPerformed
		Login venL = new Login();
		venL.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_jBCerrarSesionEgreActionPerformed

	private void jBEgrEdiInfEgrCargarInfLabEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrEdiInfEgrCargarInfLabEditarActionPerformed
		jTPEgrPestaniasInfEgresados.setEnabledAt(2, true);
		jTPEgrPestaniasInfEgresados.setSelectedIndex(2);
		jBEgrInfLabRegistrar.setEnabled(false);
		jBEgrEdiInfLAbCargarInfLabEditar.setEnabled(true);
	}// GEN-LAST:event_jBEgrEdiInfEgrCargarInfLabEditarActionPerformed

	private void jBEgrEdiInfLAbCargarInfLabEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEgrEdiInfLAbCargarInfLabEditarActionPerformed

		jBEgrInfLabRegistrar.setEnabled(true);
		jBEgrEdiInfLAbCargarInfLabEditar.setEnabled(false);
	}// GEN-LAST:event_jBEgrEdiInfLAbCargarInfLabEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLoginLogo;
    private javax.swing.JButton jBCerrarSesionEgre;
    private javax.swing.JButton jBEgrEdiInfEgrCargarInfPerEditar;
    private javax.swing.JButton jBEgrEdiInfLAbCargarInfLabEditar;
    private javax.swing.JButton jBEgrInfAcaAreasSiguiente;
    private javax.swing.JButton jBEgrInfAcaAtras;
    private javax.swing.JButton jBEgrInfLabAtras;
    private javax.swing.JButton jBEgrInfLabRegistrar;
    private javax.swing.JButton jBEgrRegEgrSiguiente;
    private javax.swing.JButton jBEgrVerOfeAplicar;
    private javax.swing.JButton jBEgrVerOfertasInteresActualizar;
    private javax.swing.JComboBox jCBEgrInfAcaFacultad;
    private javax.swing.JComboBox jCBEgrInfAcaNivelAcademicoPrograma;
    private javax.swing.JComboBox jCBEgrInfAcaProgramaAcademico;
    private javax.swing.JComboBox jCBEgrInfLabSituacionActual;
    private javax.swing.JComboBox jCBEgrInfLabTipoEmpresa;
    private javax.swing.JComboBox jCBEgrRegEgrTipoDocumento;
    private javax.swing.JComboBox jCBEgrVerOfertasInteresAreaInteres;
    private com.toedter.calendar.JDateChooser jDCEgrInfAcaFechaGrado;
    private com.toedter.calendar.JDateChooser jDCEgrInfLabFechaIngreso;
    private com.toedter.calendar.JDateChooser jDCEgrInfLabFechaSalida;
    private javax.swing.JLabel jLEgrEdiInfEgrNumeroDocumento;
    private javax.swing.JLabel jLEgrInfAcaAreasConocimientoAplicar;
    private javax.swing.JLabel jLEgrInfAcaFacultad;
    private javax.swing.JLabel jLEgrInfAcaFechaGrado;
    private javax.swing.JLabel jLEgrInfAcaNivelAcademicoPrograma;
    private javax.swing.JLabel jLEgrInfAcaNumeroDiploma;
    private javax.swing.JLabel jLEgrInfAcaProgramaAcademico;
    private javax.swing.JLabel jLEgrInfLabCargoDentroEmpresa;
    private javax.swing.JLabel jLEgrInfLabFechaIngreso;
    private javax.swing.JLabel jLEgrInfLabFechaSalida;
    private javax.swing.JLabel jLEgrInfLabNombreEmpresa;
    private javax.swing.JLabel jLEgrInfLabSectorLaboral;
    private javax.swing.JLabel jLEgrInfLabSituacionActual;
    private javax.swing.JLabel jLEgrInfLabTipoEmpresa;
    private javax.swing.JLabel jLEgrRegEgrCorreo;
    private javax.swing.JLabel jLEgrRegEgrNombres;
    private javax.swing.JLabel jLEgrRegEgrNumeroDocumento;
    private javax.swing.JLabel jLEgrRegEgrNumeroTelCel;
    private javax.swing.JLabel jLEgrRegEgrPrimerApellido;
    private javax.swing.JLabel jLEgrRegEgrSegundoApellido;
    private javax.swing.JLabel jLEgrRegEgrTipoDocumento;
    private javax.swing.JLabel jLEgrSistemaDeInformacionDeEgresados;
    private javax.swing.JLabel jLEgrSistemaDeInformacionDeEgresados1;
    private javax.swing.JLabel jLEgrVerOfertasInteresAreaInteres;
    private javax.swing.JLabel jLEgrVerOfertasInteresOfertas;
    private javax.swing.JPanel jPEgrBolsaEmpleo;
    private javax.swing.JPanel jPEgrEditarEgresados;
    private javax.swing.JPanel jPEgrInfAcademica;
    private javax.swing.JPanel jPEgrInfEmpresas;
    private javax.swing.JPanel jPEgrInfLaboral;
    private javax.swing.JPanel jPEgrRegistroEgresados;
    private javax.swing.JPanel jPEgrVerOfertaInteres;
    private javax.swing.JPanel jPPrincipalE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTAEgrInfAcaAreasConocimientoAplicar;
    private javax.swing.JTextArea jTAEgrVerOfertasInteresActualizar;
    private javax.swing.JTextField jTFEgrEdiInfEgrNumeroDocumento;
    private javax.swing.JTextField jTFEgrInfAcaNumeroDiploma;
    private javax.swing.JTextField jTFEgrInfLabNombreEmpresa;
    private javax.swing.JTextField jTFEgrInfLabSectorLaboral;
    private javax.swing.JTextField jTFEgrRegEgrCorreo;
    private javax.swing.JTextField jTFEgrRegEgrNombres;
    private javax.swing.JTextField jTFEgrRegEgrNumeroDocumento;
    private javax.swing.JTextField jTFEgrRegEgrNumeroTelCel;
    private javax.swing.JTextField jTFEgrRegEgrPrimerApellido;
    private javax.swing.JTextField jTFEgrRegEgrSegundoApellido;
    private javax.swing.JTextField jTFLEgrInfLabCargoDentroEmpresa;
    private javax.swing.JTabbedPane jTPEgrPestaniasBolsaDeEmpleo;
    private javax.swing.JTabbedPane jTPEgrPestaniasInfEgresados;
    private javax.swing.JTabbedPane jTPEgrPestaniasPrincipales;
    // End of variables declaration//GEN-END:variables
	
	

	private void cargarEmpresas() {
		try{
    		jCBEgrInfLabTipoEmpresa.removeAllItems();
	    	List<Empresa> lista = controlador.listarEmpresas();
	    	for (Empresa sl : lista) {
	    		jCBEgrInfLabTipoEmpresa.addItem(sl);
			}
    	}catch(Exception e){
    		e.printStackTrace();
    	}
		
	}

	private void cargarFacultades() {
		try{
	    	jCBEgrInfAcaProgramaAcademico.removeAllItems();
	    	List<Facultad> lista = controlador.listarFacultades();
	    	for (Facultad facultad : lista) {
	    		jCBEgrInfAcaProgramaAcademico.addItem(facultad);
			}
    	}catch(Exception e){
    		e.printStackTrace();
    	}
	}
	public void limpiarCampos(){
    	
    	//jTCelular.setText(null);
    	//jCBDocumento1.setSelectedIndex(0);
    	
    }
}
