/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.desarrollo.SDIDE.vista.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.List;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.sound.midi.SysexMessage;


import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Ciudad;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Contacto;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Departamento;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Empresa;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.Pais;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.entidades.SectorLaboral;
import co.edu.eam.ingesoft.desarrollo.SDIDE.persistencia.modelo.enumeraciones.TipoEmpresa;
import co.edu.eam.ingesoft.desarrollo.SDIDE.vista.controlador.ControladorAdminContactoEmpresa;

/**
 *
 * @author user
 */
public class VentanaContactoEmpresa extends javax.swing.JFrame {

	private ControladorAdminContactoEmpresa controlador;
	/**
	 * Creates new form VentanaContactoEmpresa
	 */
	public VentanaContactoEmpresa() {
		initComponents();
		setVisible(true);
		setResizable(false);
		this.setLocationRelativeTo(this);
		this.setResizable(false);
		this.setName("Ventana del Contacto de la Empresa");
        controlador = new ControladorAdminContactoEmpresa();
		jCBEmpRegEmpTipoEmpresa.addItem("Seleccione un tipo");
		jCBEmpRegEmpTipoEmpresa.addItem(TipoEmpresa.Privada);
		jCBEmpRegEmpTipoEmpresa.addItem(TipoEmpresa.Publica);
        listarPaises();
        listarDepartamentos();
		listarCiudades();
		listarSectorLaboral();
		
        
	}

	

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        jPPrincipalC = new javax.swing.JPanel();
        jTPEAMPestaniasPrincipales = new javax.swing.JTabbedPane();
        jPEmpInfEmpresas = new javax.swing.JPanel();
        jTPEmpPestaniasInfEmpresas = new javax.swing.JTabbedPane();
        jPEmpRegistroEmpresasDatoEmpresa = new javax.swing.JPanel();
        jTFEmpRegEmpRazonSocial = new javax.swing.JTextField();
        jLEmpRegEmpRazonSocial = new javax.swing.JLabel();
        jLEmpRegEmpTipoEmpresa = new javax.swing.JLabel();
        jLEmpRegEmpPais = new javax.swing.JLabel();
        jTFEmpRegEmpTelefono = new javax.swing.JTextField();
        jLEmpRegEmpTelefono = new javax.swing.JLabel();
        jTFEmpRegEmpNIT = new javax.swing.JTextField();
        jLEmpRegEmpNIT = new javax.swing.JLabel();
        jLEmpRegEmpDepartamento = new javax.swing.JLabel();
        jLEmpRegEmpCiudad = new javax.swing.JLabel();
        jTFEmpRegEmpSitioWeb = new javax.swing.JTextField();
        jLEmpRegEmpSitioWeb = new javax.swing.JLabel();
        jLEmpRegEmpSectorLaboral = new javax.swing.JLabel();
        jTFEmpRegEmpDireccion = new javax.swing.JTextField();
        jLEmpRegEmpDireccion = new javax.swing.JLabel();
        jCBEmpRegEmpTipoEmpresa = new javax.swing.JComboBox();
        jBEmpRegEmpSiguiente = new javax.swing.JButton();
        jCBEmpRegEmpPais = new javax.swing.JComboBox();
        jCBEmpRegEmpCiudad = new javax.swing.JComboBox();
        jCBEmpRegEmpDeportamento = new javax.swing.JComboBox();
        jCBEmpRegEmpSectorLaboral = new javax.swing.JComboBox();
        jPEmpRegistroEmpresasDatoContacto = new javax.swing.JPanel();
        jTFEmpRegEmpContNomCompleto = new javax.swing.JTextField();
        jLEmpRegEmpContNomCompleto = new javax.swing.JLabel();
        jTFEmpRegEmpContCorreo = new javax.swing.JTextField();
        jLEmpRegEmpContCorreo = new javax.swing.JLabel();
        jTFEmpRegEmpContCargoEmpresa = new javax.swing.JTextField();
        jLEmpRegEmpContCargoEmpresa = new javax.swing.JLabel();
        jTFEmpRegEmpContTelefono = new javax.swing.JTextField();
        jLEmpRegEmpContTelefono = new javax.swing.JLabel();
        jBEmpRegEmpContRegistrar = new javax.swing.JButton();
        jBEmpRegEmpContAtras = new javax.swing.JButton();
        jBEmpEdiEmpEditar = new javax.swing.JButton();
        jPEmpEditarEmpresa = new javax.swing.JPanel();
        jTFEmpEdiEmpNIT = new javax.swing.JTextField();
        jLEmpEdiEmpNIT = new javax.swing.JLabel();
        jBEmpEdiEmpCargarInformacionEditar = new javax.swing.JButton();
        jPEmpBolsaEmpleo = new javax.swing.JPanel();
        jTPEmpPestaniasBolsaEmpleo = new javax.swing.JTabbedPane();
        jPEmpRegistroOferta = new javax.swing.JPanel();
        jTFEmpRegOfeCiudadOferta = new javax.swing.JTextField();
        jLEmpRegOfeCiudadOferta = new javax.swing.JLabel();
        jTFEmpRegOfeRequerimentosOferta = new javax.swing.JTextField();
        jLEmpRegOfeRequerimentosOferta = new javax.swing.JLabel();
        jLEmpRegOfeCargoOfrecer = new javax.swing.JLabel();
        jTFEmpRegOfeSalario = new javax.swing.JTextField();
        jLEmpRegOfeSalario = new javax.swing.JLabel();
        jLEmpRegOfeFechaGrado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAEmpRegOfeResumen = new javax.swing.JTextArea();
        jLEmpRegOfeResumen = new javax.swing.JLabel();
        jLEmpRegOfeAreaConocimiento = new javax.swing.JLabel();
        jTFEmpRegOfeCargoOfrecer = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAEmpRegOfeDescripcionOferta = new javax.swing.JTextArea();
        jLEmpRegOfeDescripcionOferta = new javax.swing.JLabel();
        jBEmpRegOfeRegistrar = new javax.swing.JButton();
        jCBEmpRegOfeAreaConocimiento = new javax.swing.JComboBox();
        jDCEmpRegOfeFechaGrado = new com.toedter.calendar.JDateChooser();
        jPEmpCerrarOferta = new javax.swing.JPanel();
        jLEmpCerOfeOferta = new javax.swing.JLabel();
        jBEmpCerOfeCerrarOferta = new javax.swing.JButton();
        jBEmpCerOfeActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAEmpCerOfeOferta = new javax.swing.JTextArea();
        jPEmpAplicarOferta = new javax.swing.JPanel();
        jLEmpAplOfeOfertas = new javax.swing.JLabel();
        jLEmpAplOfeAreaInteres = new javax.swing.JLabel();
        jCBEmpAplOfeAreaInteres = new javax.swing.JComboBox();
        jBEmpAplOfeVerDatos = new javax.swing.JButton();
        jBEmpAplOfeAplicar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAEmpAplOfeOfertas = new javax.swing.JTextArea();
        jPEmpInfParametricas = new javax.swing.JPanel();
        jTPEmpPestaniasInfParametrica = new javax.swing.JTabbedPane();
        jPEmpGestionAreaInteres = new javax.swing.JPanel();
        jLEmpGesAreIntNombreAreaInteres = new javax.swing.JLabel();
        jBEmpGesAreIntCrear = new javax.swing.JButton();
        jBEmpGesAreIntEliminar = new javax.swing.JButton();
        jTFEmpGesAreIntNombreAreaInteres = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAEmpListarAreInteres = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLEmpSistemaDeInformacionDeEgresados = new javax.swing.JLabel();
        ImgLoginLogo = new javax.swing.JLabel();
        jLEmpSistemaDeInformacionDeEgresados1 = new javax.swing.JLabel();
        jBCerrarSesionConEmp = new javax.swing.JButton();

     

        jPPrincipalC.setBackground(new java.awt.Color(255, 255, 255));

        jTPEAMPestaniasPrincipales.setBackground(new java.awt.Color(255, 255, 255));
        jTPEAMPestaniasPrincipales.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N

        jPEmpInfEmpresas.setBackground(new java.awt.Color(255, 255, 255));

        jTPEmpPestaniasInfEmpresas.setBackground(new java.awt.Color(255, 255, 255));
        jTPEmpPestaniasInfEmpresas.setFont(new java.awt.Font("Meiryo", 2, 11)); // NOI18N

        jPEmpRegistroEmpresasDatoEmpresa.setBackground(new java.awt.Color(255, 255, 255));

        jTFEmpRegEmpRazonSocial.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpRazonSocial.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpRazonSocial.setText("Razón Social:");

        jLEmpRegEmpTipoEmpresa.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpTipoEmpresa.setText("Tipo de Empresa:");

        jLEmpRegEmpPais.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpPais.setText("País:");

        jTFEmpRegEmpTelefono.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpTelefono.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpTelefono.setText("Teléfono:");

        jTFEmpRegEmpNIT.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpNIT.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpNIT.setText("NIT:");

        jLEmpRegEmpDepartamento.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpDepartamento.setText("Departamento:");

        jLEmpRegEmpCiudad.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpCiudad.setText("Ciudad:");

        jTFEmpRegEmpSitioWeb.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpSitioWeb.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpSitioWeb.setText("Dirección Sitio Web:");

        jLEmpRegEmpSectorLaboral.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpSectorLaboral.setText("Sector Laboral:");

        jTFEmpRegEmpDireccion.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpDireccion.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpDireccion.setText("Dirección:");

        jCBEmpRegEmpTipoEmpresa.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpRegEmpTipoEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Tipo de Empresa", "Pública ", "Privada" }));

        jBEmpRegEmpSiguiente.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpRegEmpSiguiente.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpRegEmpSiguiente.setText("Siguiente");
        jBEmpRegEmpSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpRegEmpSiguienteActionPerformed(evt);
            }
        });

        jCBEmpRegEmpPais.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpRegEmpPais.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Pais", "Colombia", "Guatemala", "Chile", "Ecuador", "Argentina" }));

        jCBEmpRegEmpCiudad.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpRegEmpCiudad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Ciudad", "Armenia", "Cali", "Pereira", "Medellin", "Bogota", " " }));

        jCBEmpRegEmpDeportamento.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpRegEmpDeportamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un Departamento", "Quindio", "Caldas", "Valle" }));

        jCBEmpRegEmpSectorLaboral.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpRegEmpSectorLaboral.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un sector" }));

        javax.swing.GroupLayout jPEmpRegistroEmpresasDatoEmpresaLayout = new javax.swing.GroupLayout(jPEmpRegistroEmpresasDatoEmpresa);
        jPEmpRegistroEmpresasDatoEmpresa.setLayout(jPEmpRegistroEmpresasDatoEmpresaLayout);
        jPEmpRegistroEmpresasDatoEmpresaLayout.setHorizontalGroup(
            jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpNIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmpRegEmpNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmpRegEmpTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpRazonSocial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmpRegEmpRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpPais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEmpRegEmpPais, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEmpRegEmpDeportamento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpSitioWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmpRegEmpSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpSectorLaboral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEmpRegEmpSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegEmpDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFEmpRegEmpDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEmpRegEmpCiudad)
                            .addComponent(jLEmpRegEmpTipoEmpresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBEmpRegEmpTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBEmpRegEmpCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBEmpRegEmpSiguiente)
                .addGap(21, 21, 21))
        );
        jPEmpRegistroEmpresasDatoEmpresaLayout.setVerticalGroup(
            jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpRazonSocial)
                            .addComponent(jTFEmpRegEmpRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpPais)
                            .addComponent(jCBEmpRegEmpPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpTelefono)
                            .addComponent(jTFEmpRegEmpTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpNIT)
                            .addComponent(jTFEmpRegEmpNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpDepartamento)
                            .addComponent(jCBEmpRegEmpDeportamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createSequentialGroup()
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBEmpRegEmpTipoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEmpRegEmpTipoEmpresa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpCiudad)
                            .addComponent(jCBEmpRegEmpCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpSitioWeb)
                            .addComponent(jTFEmpRegEmpSitioWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpSectorLaboral)
                            .addComponent(jCBEmpRegEmpSectorLaboral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroEmpresasDatoEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpRegEmpDireccion)
                            .addComponent(jTFEmpRegEmpDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20)
                .addComponent(jBEmpRegEmpSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTPEmpPestaniasInfEmpresas.addTab("Registrar de la Empresa(Datos de la Empresa)", jPEmpRegistroEmpresasDatoEmpresa);

        jPEmpRegistroEmpresasDatoContacto.setBackground(new java.awt.Color(255, 255, 255));

        jTFEmpRegEmpContNomCompleto.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpContNomCompleto.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpContNomCompleto.setText("Nombre Completo:");

        jTFEmpRegEmpContCorreo.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpContCorreo.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpContCorreo.setText("Correo Electrónico:");

        jTFEmpRegEmpContCargoEmpresa.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpContCargoEmpresa.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpContCargoEmpresa.setText("Cargo en la Empresa:");

        jTFEmpRegEmpContTelefono.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegEmpContTelefono.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegEmpContTelefono.setText("Teléfono:");

        jBEmpRegEmpContRegistrar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpRegEmpContRegistrar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpRegEmpContRegistrar.setText("Registar");
        jBEmpRegEmpContRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpRegEmpContRegistrarActionPerformed(evt);
            }
        });

        jBEmpRegEmpContAtras.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpRegEmpContAtras.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpRegEmpContAtras.setText("Atras");
        jBEmpRegEmpContAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpRegEmpContAtrasActionPerformed(evt);
            }
        });

        jBEmpEdiEmpEditar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpEdiEmpEditar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpEdiEmpEditar.setText("Editar");
        jBEmpEdiEmpEditar.setEnabled(false);
        jBEmpEdiEmpEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpEdiEmpEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEmpRegistroEmpresasDatoContactoLayout = new javax.swing.GroupLayout(jPEmpRegistroEmpresasDatoContacto);
        jPEmpRegistroEmpresasDatoContacto.setLayout(jPEmpRegistroEmpresasDatoContactoLayout);
        jPEmpRegistroEmpresasDatoContactoLayout.setHorizontalGroup(
            jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                        .addComponent(jBEmpRegEmpContAtras)
                        .addGap(261, 261, 261)
                        .addComponent(jBEmpRegEmpContRegistrar)
                        .addGap(68, 68, 68)
                        .addComponent(jBEmpEdiEmpEditar))
                    .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                            .addComponent(jLEmpRegEmpContTelefono)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTFEmpRegEmpContTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                            .addComponent(jLEmpRegEmpContCargoEmpresa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTFEmpRegEmpContCargoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                                .addComponent(jLEmpRegEmpContNomCompleto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEmpRegEmpContNomCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                                .addComponent(jLEmpRegEmpContCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEmpRegEmpContCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPEmpRegistroEmpresasDatoContactoLayout.setVerticalGroup(
            jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpRegEmpContNomCompleto)
                    .addComponent(jTFEmpRegEmpContNomCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpRegEmpContCorreo)
                    .addComponent(jTFEmpRegEmpContCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpRegEmpContCargoEmpresa)
                    .addComponent(jTFEmpRegEmpContCargoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpRegEmpContTelefono)
                    .addComponent(jTFEmpRegEmpContTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPEmpRegistroEmpresasDatoContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEmpRegEmpContAtras)
                    .addComponent(jBEmpRegEmpContRegistrar)
                    .addComponent(jBEmpEdiEmpEditar))
                .addGap(71, 71, 71))
        );

        jTPEmpPestaniasInfEmpresas.addTab("Registrar de la Empresa(Datos del Contacto)", jPEmpRegistroEmpresasDatoContacto);

        jPEmpEditarEmpresa.setBackground(new java.awt.Color(255, 255, 255));

        jTFEmpEdiEmpNIT.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpEdiEmpNIT.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpEdiEmpNIT.setText("NIT de la Empresa:");

        jBEmpEdiEmpCargarInformacionEditar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpEdiEmpCargarInformacionEditar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpEdiEmpCargarInformacionEditar.setText("Cargar Información a Editar");
        jBEmpEdiEmpCargarInformacionEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpEdiEmpCargarInformacionEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPEmpEditarEmpresaLayout = new javax.swing.GroupLayout(jPEmpEditarEmpresa);
        jPEmpEditarEmpresa.setLayout(jPEmpEditarEmpresaLayout);
        jPEmpEditarEmpresaLayout.setHorizontalGroup(
            jPEmpEditarEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpEditarEmpresaLayout.createSequentialGroup()
                .addGroup(jPEmpEditarEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpEditarEmpresaLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLEmpEdiEmpNIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFEmpEdiEmpNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPEmpEditarEmpresaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jBEmpEdiEmpCargarInformacionEditar)))
                .addContainerGap(442, Short.MAX_VALUE))
        );
        jPEmpEditarEmpresaLayout.setVerticalGroup(
            jPEmpEditarEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpEditarEmpresaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPEmpEditarEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpEdiEmpNIT)
                    .addComponent(jTFEmpEdiEmpNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jBEmpEdiEmpCargarInformacionEditar)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTPEmpPestaniasInfEmpresas.addTab("Editar la Información de la Empresa", jPEmpEditarEmpresa);

        javax.swing.GroupLayout jPEmpInfEmpresasLayout = new javax.swing.GroupLayout(jPEmpInfEmpresas);
        jPEmpInfEmpresas.setLayout(jPEmpInfEmpresasLayout);
        jPEmpInfEmpresasLayout.setHorizontalGroup(
            jPEmpInfEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEmpPestaniasInfEmpresas)
        );
        jPEmpInfEmpresasLayout.setVerticalGroup(
            jPEmpInfEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpInfEmpresasLayout.createSequentialGroup()
                .addComponent(jTPEmpPestaniasInfEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTPEAMPestaniasPrincipales.addTab("Información de Empresas", jPEmpInfEmpresas);

        jPEmpBolsaEmpleo.setBackground(new java.awt.Color(255, 255, 255));

        jTPEmpPestaniasBolsaEmpleo.setFont(new java.awt.Font("Meiryo", 2, 11)); // NOI18N

        jPEmpRegistroOferta.setBackground(new java.awt.Color(255, 255, 255));

        jTFEmpRegOfeCiudadOferta.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegOfeCiudadOferta.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeCiudadOferta.setText("Ciudad de la Oferta:");

        jTFEmpRegOfeRequerimentosOferta.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegOfeRequerimentosOferta.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeRequerimentosOferta.setText("Requerimientos de la Oferta:");

        jLEmpRegOfeCargoOfrecer.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeCargoOfrecer.setText("Cargo a Ofrecer:");

        jTFEmpRegOfeSalario.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jLEmpRegOfeSalario.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeSalario.setText("Salario:");

        jLEmpRegOfeFechaGrado.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeFechaGrado.setText("Fecha de Grado:");

        jTAEmpRegOfeResumen.setColumns(20);
        jTAEmpRegOfeResumen.setFont(new java.awt.Font("Meiryo", 0, 12)); // NOI18N
        jTAEmpRegOfeResumen.setRows(5);
        jScrollPane2.setViewportView(jTAEmpRegOfeResumen);

        jLEmpRegOfeResumen.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeResumen.setText("Resumen:");

        jLEmpRegOfeAreaConocimiento.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeAreaConocimiento.setText("Área de Conocimiento:");

        jTFEmpRegOfeCargoOfrecer.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jTAEmpRegOfeDescripcionOferta.setColumns(20);
        jTAEmpRegOfeDescripcionOferta.setFont(new java.awt.Font("Meiryo", 0, 12)); // NOI18N
        jTAEmpRegOfeDescripcionOferta.setRows(5);
        jScrollPane3.setViewportView(jTAEmpRegOfeDescripcionOferta);

        jLEmpRegOfeDescripcionOferta.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpRegOfeDescripcionOferta.setText("Descripción de la Oferta:");

        jBEmpRegOfeRegistrar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpRegOfeRegistrar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpRegOfeRegistrar.setText("Registar");
        jBEmpRegOfeRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpRegOfeRegistrarActionPerformed(evt);
            }
        });

        jCBEmpRegOfeAreaConocimiento.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpRegOfeAreaConocimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Área" }));

        javax.swing.GroupLayout jPEmpRegistroOfertaLayout = new javax.swing.GroupLayout(jPEmpRegistroOferta);
        jPEmpRegistroOferta.setLayout(jPEmpRegistroOfertaLayout);
        jPEmpRegistroOfertaLayout.setHorizontalGroup(
            jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegOfeCargoOfrecer)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpRegistroOfertaLayout.createSequentialGroup()
                        .addComponent(jLEmpRegOfeSalario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFEmpRegOfeSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFEmpRegOfeCargoOfrecer, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                                .addComponent(jLEmpRegOfeCiudadOferta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEmpRegOfeCiudadOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                                .addComponent(jLEmpRegOfeRequerimentosOferta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEmpRegOfeRequerimentosOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLEmpRegOfeFechaGrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDCEmpRegOfeFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                        .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                                .addComponent(jLEmpRegOfeAreaConocimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEmpRegOfeAreaConocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLEmpRegOfeResumen))
                        .addGap(11, 11, 11)
                        .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEmpRegOfeDescripcionOferta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBEmpRegOfeRegistrar)
                .addGap(47, 47, 47))
        );
        jPEmpRegistroOfertaLayout.setVerticalGroup(
            jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPEmpRegistroOfertaLayout.createSequentialGroup()
                        .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEmpRegOfeResumen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLEmpRegOfeDescripcionOferta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpRegistroOfertaLayout.createSequentialGroup()
                                .addComponent(jBEmpRegOfeRegistrar)
                                .addGap(38, 38, 38))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpRegOfeAreaConocimiento)
                    .addComponent(jCBEmpRegOfeAreaConocimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmpRegOfeCiudadOferta)
                    .addComponent(jTFEmpRegOfeCiudadOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpRegOfeCargoOfrecer)
                    .addComponent(jTFEmpRegOfeCargoOfrecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmpRegOfeRequerimentosOferta)
                    .addComponent(jTFEmpRegOfeRequerimentosOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPEmpRegistroOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEmpRegOfeSalario)
                        .addComponent(jTFEmpRegOfeSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLEmpRegOfeFechaGrado)
                    .addComponent(jDCEmpRegOfeFechaGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTPEmpPestaniasBolsaEmpleo.addTab("Registrar una Oferta", jPEmpRegistroOferta);

        jPEmpCerrarOferta.setBackground(new java.awt.Color(255, 255, 255));

        jLEmpCerOfeOferta.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpCerOfeOferta.setText("Ofertas:");

        jBEmpCerOfeCerrarOferta.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpCerOfeCerrarOferta.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpCerOfeCerrarOferta.setText("Cerrar Oferta Seleccionada");
        jBEmpCerOfeCerrarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpCerOfeCerrarOfertaActionPerformed(evt);
            }
        });

        jBEmpCerOfeActualizar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpCerOfeActualizar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpCerOfeActualizar.setText("Actualizar");
        jBEmpCerOfeActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpCerOfeActualizarActionPerformed(evt);
            }
        });

        jTAEmpCerOfeOferta.setColumns(20);
        jTAEmpCerOfeOferta.setRows(5);
        jScrollPane1.setViewportView(jTAEmpCerOfeOferta);

        javax.swing.GroupLayout jPEmpCerrarOfertaLayout = new javax.swing.GroupLayout(jPEmpCerrarOferta);
        jPEmpCerrarOferta.setLayout(jPEmpCerrarOfertaLayout);
        jPEmpCerrarOfertaLayout.setHorizontalGroup(
            jPEmpCerrarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPEmpCerrarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEmpCerOfeOferta)
                    .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPEmpCerrarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jBEmpCerOfeCerrarOferta))
                            .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jBEmpCerOfeActualizar)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPEmpCerrarOfertaLayout.setVerticalGroup(
            jPEmpCerrarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                .addGroup(jPEmpCerrarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLEmpCerOfeOferta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPEmpCerrarOfertaLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jBEmpCerOfeActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jBEmpCerOfeCerrarOferta)
                        .addGap(0, 78, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTPEmpPestaniasBolsaEmpleo.addTab("Cerrar una Oferta", jPEmpCerrarOferta);

        jPEmpAplicarOferta.setBackground(new java.awt.Color(255, 255, 255));

        jLEmpAplOfeOfertas.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpAplOfeOfertas.setText("Ofertas:");

        jLEmpAplOfeAreaInteres.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpAplOfeAreaInteres.setText("Áreas de Interés :");

        jCBEmpAplOfeAreaInteres.setFont(new java.awt.Font("Meiryo", 0, 10)); // NOI18N
        jCBEmpAplOfeAreaInteres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Área" }));

        jBEmpAplOfeVerDatos.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpAplOfeVerDatos.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpAplOfeVerDatos.setText("Ver Datos del Egresado");
        jBEmpAplOfeVerDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpAplOfeVerDatosActionPerformed(evt);
            }
        });

        jBEmpAplOfeAplicar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpAplOfeAplicar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpAplOfeAplicar.setText("Aplicar");
        jBEmpAplOfeAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpAplOfeAplicarActionPerformed(evt);
            }
        });

        jTAEmpAplOfeOfertas.setColumns(20);
        jTAEmpAplOfeOfertas.setRows(5);
        jScrollPane4.setViewportView(jTAEmpAplOfeOfertas);

        javax.swing.GroupLayout jPEmpAplicarOfertaLayout = new javax.swing.GroupLayout(jPEmpAplicarOferta);
        jPEmpAplicarOferta.setLayout(jPEmpAplicarOfertaLayout);
        jPEmpAplicarOfertaLayout.setHorizontalGroup(
            jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpAplicarOfertaLayout.createSequentialGroup()
                .addGroup(jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpAplicarOfertaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLEmpAplOfeAreaInteres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBEmpAplOfeAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpAplicarOfertaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEmpAplOfeVerDatos, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpAplicarOfertaLayout.createSequentialGroup()
                                .addComponent(jBEmpAplOfeAplicar)
                                .addGap(56, 56, 56)))
                        .addGap(18, 18, 18)))
                .addGroup(jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEmpAplOfeOfertas)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPEmpAplicarOfertaLayout.setVerticalGroup(
            jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpAplicarOfertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLEmpAplOfeOfertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPEmpAplicarOfertaLayout.createSequentialGroup()
                        .addGroup(jPEmpAplicarOfertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEmpAplOfeAreaInteres)
                            .addComponent(jCBEmpAplOfeAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jBEmpAplOfeVerDatos)
                        .addGap(34, 34, 34)
                        .addComponent(jBEmpAplOfeAplicar))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTPEmpPestaniasBolsaEmpleo.addTab("Aplicados a una Oferta", jPEmpAplicarOferta);

        javax.swing.GroupLayout jPEmpBolsaEmpleoLayout = new javax.swing.GroupLayout(jPEmpBolsaEmpleo);
        jPEmpBolsaEmpleo.setLayout(jPEmpBolsaEmpleoLayout);
        jPEmpBolsaEmpleoLayout.setHorizontalGroup(
            jPEmpBolsaEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEmpPestaniasBolsaEmpleo)
        );
        jPEmpBolsaEmpleoLayout.setVerticalGroup(
            jPEmpBolsaEmpleoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEmpPestaniasBolsaEmpleo)
        );

        jTPEAMPestaniasPrincipales.addTab("Bolsa de Empleo", jPEmpBolsaEmpleo);

        jPEmpInfParametricas.setBackground(new java.awt.Color(255, 255, 255));

        jTPEmpPestaniasInfParametrica.setBackground(new java.awt.Color(255, 255, 255));
        jTPEmpPestaniasInfParametrica.setFont(new java.awt.Font("Meiryo", 2, 11)); // NOI18N

        jPEmpGestionAreaInteres.setBackground(new java.awt.Color(255, 255, 255));

        jLEmpGesAreIntNombreAreaInteres.setFont(new java.awt.Font("Meiryo", 1, 11)); // NOI18N
        jLEmpGesAreIntNombreAreaInteres.setText("Nombre de el Áreas de Interés:");

        jBEmpGesAreIntCrear.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpGesAreIntCrear.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpGesAreIntCrear.setText("Crear");
        jBEmpGesAreIntCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpGesAreIntCrearActionPerformed(evt);
            }
        });

        jBEmpGesAreIntEliminar.setBackground(new java.awt.Color(102, 204, 255));
        jBEmpGesAreIntEliminar.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBEmpGesAreIntEliminar.setText("Eliminar");
        jBEmpGesAreIntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmpGesAreIntEliminarActionPerformed(evt);
            }

			
        });

        jTFEmpGesAreIntNombreAreaInteres.setFont(new java.awt.Font("Meiryo", 0, 11)); // NOI18N

        jTAEmpListarAreInteres.setColumns(20);
        jTAEmpListarAreInteres.setRows(5);
        jScrollPane5.setViewportView(jTAEmpListarAreInteres);

        javax.swing.GroupLayout jPEmpGestionAreaInteresLayout = new javax.swing.GroupLayout(jPEmpGestionAreaInteres);
        jPEmpGestionAreaInteres.setLayout(jPEmpGestionAreaInteresLayout);
        jPEmpGestionAreaInteresLayout.setHorizontalGroup(
            jPEmpGestionAreaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPEmpGestionAreaInteresLayout.createSequentialGroup()
                .addGroup(jPEmpGestionAreaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPEmpGestionAreaInteresLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBEmpGesAreIntEliminar))
                    .addGroup(jPEmpGestionAreaInteresLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPEmpGestionAreaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBEmpGesAreIntCrear)
                            .addGroup(jPEmpGestionAreaInteresLayout.createSequentialGroup()
                                .addComponent(jLEmpGesAreIntNombreAreaInteres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFEmpGesAreIntNombreAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
        );
        jPEmpGestionAreaInteresLayout.setVerticalGroup(
            jPEmpGestionAreaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPEmpGestionAreaInteresLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPEmpGestionAreaInteresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEmpGesAreIntNombreAreaInteres)
                    .addComponent(jTFEmpGesAreIntNombreAreaInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jBEmpGesAreIntCrear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPEmpGestionAreaInteresLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBEmpGesAreIntEliminar)
                .addContainerGap())
        );

        jTPEmpPestaniasInfParametrica.addTab("Gestionar Áreas de Interés", jPEmpGestionAreaInteres);

        javax.swing.GroupLayout jPEmpInfParametricasLayout = new javax.swing.GroupLayout(jPEmpInfParametricas);
        jPEmpInfParametricas.setLayout(jPEmpInfParametricasLayout);
        jPEmpInfParametricasLayout.setHorizontalGroup(
            jPEmpInfParametricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEmpPestaniasInfParametrica)
        );
        jPEmpInfParametricasLayout.setVerticalGroup(
            jPEmpInfParametricasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTPEmpPestaniasInfParametrica)
        );

        jTPEAMPestaniasPrincipales.addTab("Información Paramétrica", jPEmpInfParametricas);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLEmpSistemaDeInformacionDeEgresados.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLEmpSistemaDeInformacionDeEgresados.setForeground(new java.awt.Color(255, 255, 255));
        jLEmpSistemaDeInformacionDeEgresados.setText("De Egresados ");

        ImgLoginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_eam.png"))); // NOI18N

        jLEmpSistemaDeInformacionDeEgresados1.setFont(new java.awt.Font("Meiryo", 1, 36)); // NOI18N
        jLEmpSistemaDeInformacionDeEgresados1.setForeground(new java.awt.Color(255, 255, 255));
        jLEmpSistemaDeInformacionDeEgresados1.setText("Sistema De Información ");

        jBCerrarSesionConEmp.setBackground(new java.awt.Color(0, 0, 51));
        jBCerrarSesionConEmp.setFont(new java.awt.Font("Meiryo", 1, 12)); // NOI18N
        jBCerrarSesionConEmp.setForeground(new java.awt.Color(153, 153, 153));
        jBCerrarSesionConEmp.setText("Cerrar Sesion");
        jBCerrarSesionConEmp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        jBCerrarSesionConEmp.setBorderPainted(false);
        jBCerrarSesionConEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCerrarSesionConEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLEmpSistemaDeInformacionDeEgresados1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLEmpSistemaDeInformacionDeEgresados)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBCerrarSesionConEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ImgLoginLogo))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImgLoginLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLEmpSistemaDeInformacionDeEgresados1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLEmpSistemaDeInformacionDeEgresados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCerrarSesionConEmp)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPPrincipalCLayout = new javax.swing.GroupLayout(jPPrincipalC);
        jPPrincipalC.setLayout(jPPrincipalCLayout);
        jPPrincipalCLayout.setHorizontalGroup(
            jPPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPPrincipalCLayout.createSequentialGroup()
                .addComponent(jTPEAMPestaniasPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPPrincipalCLayout.setVerticalGroup(
            jPPrincipalCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPrincipalCLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPEAMPestaniasPrincipales, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPPrincipalC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        

        pack();
    }// </editor-fold>//GEN-END:initComponents
	private void jBEmpGesAreIntEliminarActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	private void jBEmpRegEmpSiguienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpRegEmpSiguienteActionPerformed

		jTPEmpPestaniasInfEmpresas.setEnabledAt(1, true);
		jTPEmpPestaniasInfEmpresas.setSelectedIndex(1);

	}// GEN-LAST:event_jBEmpRegEmpSiguienteActionPerformed

	private void jBEmpRegEmpContAtrasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpRegEmpContAtrasActionPerformed
		jTPEmpPestaniasInfEmpresas.setEnabledAt(0, true);
		jTPEmpPestaniasInfEmpresas.setSelectedIndex(0);
	}// GEN-LAST:event_jBEmpRegEmpContAtrasActionPerformed

	private void jBEmpRegEmpContRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpRegEmpContRegistrarActionPerformed
		try {
			if (jTFEmpRegEmpNIT.getText().isEmpty() || jCBEmpRegEmpSectorLaboral.getSelectedIndex() == 0
					|| jCBEmpRegEmpCiudad.getSelectedIndex() == 0 || jCBEmpRegEmpDeportamento.getSelectedIndex() == 0
					||jCBEmpRegEmpPais.getSelectedIndex() == 0
					|| jTFEmpRegEmpRazonSocial.getText().isEmpty() || jTFEmpRegEmpTelefono.getText().isEmpty()
					|| jCBEmpRegEmpTipoEmpresa.getSelectedIndex() == 0 || jTFEmpRegEmpDireccion.getText().isEmpty()
					|| jTFEmpRegEmpSitioWeb.getText().isEmpty()
					||jTFEmpRegEmpContNomCompleto.getText().isEmpty()
					||jTFEmpRegEmpContCorreo.getText().isEmpty()
					||jTFEmpRegEmpContCargoEmpresa.getText().isEmpty()
					||jTFEmpRegEmpContTelefono.getText().isEmpty()
					) {
				JOptionPane.showMessageDialog(null, "Asegurese de ingresar todos los datos");
			} else {
				
		jTPEmpPestaniasInfEmpresas.setEnabledAt(0, true);
		jTPEmpPestaniasInfEmpresas.setSelectedIndex(0);
		
		String nit = jTFEmpRegEmpNIT.getText();
		SectorLaboral sec = (SectorLaboral) jCBEmpRegEmpSectorLaboral.getSelectedItem();
		Ciudad ciudad = (Ciudad) jCBEmpRegEmpCiudad.getSelectedItem();
		Departamento dep = (Departamento) jCBEmpRegEmpDeportamento.getSelectedItem();
		Pais pai = (Pais) jCBEmpRegEmpPais.getSelectedItem();
		String razonSocial = jTFEmpRegEmpRazonSocial.getText();
		String tel = jTFEmpRegEmpTelefono.getText();
		TipoEmpresa tipo = (TipoEmpresa) jCBEmpRegEmpTipoEmpresa.getSelectedItem();
		String sitioWeb = jTFEmpRegEmpSitioWeb.getText();
		String dirEmp = jTFEmpRegEmpDireccion.getText();
		Empresa empresa = new Empresa(nit,sec,ciudad,dep,pai,razonSocial,tel,tipo,dirEmp,sitioWeb);

		controlador.crearEmpresa(empresa);

		// contacto
		String nom = jTFEmpRegEmpContNomCompleto.getText();
		String email = jTFEmpRegEmpContCorreo.getText();
		String cargo = jTFEmpRegEmpContCargoEmpresa.getText();
		String telef = jTFEmpRegEmpContTelefono.getText();
		Contacto con = new Contacto(empresa, nom, email, cargo, telef);
		
		controlador.crearContacto(con, empresa);
		JOptionPane.showMessageDialog(null, "Se regisrto con exito");
		limpiarCampos();
			}
		
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		
	}// GEN-LAST:event_jBEmpRegEmpContRegistrarActionPerformed

	private void jBEmpEdiEmpCargarInformacionEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpEdiEmpCargarInformacionEditarActionPerformed
		try{
		if (jTFEmpEdiEmpNIT.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Ingrese el Nit de la empresa");
		
		
		} else {
	    jTPEmpPestaniasInfEmpresas.setEnabledAt(0, true);
		jTPEmpPestaniasInfEmpresas.setSelectedIndex(0);
		jBEmpEdiEmpEditar.setEnabled(true);
		jBEmpRegEmpContRegistrar.setEnabled(false);
			
			String nit = jTFEmpEdiEmpNIT.getText();
			Empresa em = controlador.buscarEmpresa(nit);
			Contacto con = controlador.buscarContacto(nit);

			if ((em != null) && (con != null)) {
				jTFEmpRegEmpNIT.setText(em.getIdEmpresa());
				jCBEmpRegEmpSectorLaboral.setSelectedItem(em.getIdSectorLaboral());
				jCBEmpRegEmpCiudad.setSelectedItem(em.getIdCiudad());
				jCBEmpRegEmpDeportamento.setSelectedItem(em.getIdDepartamento());
				jCBEmpRegEmpPais.setSelectedItem(em.getIdPais());
				jTFEmpRegEmpRazonSocial.setText(em.getRazonSocial());
				jTFEmpRegEmpTelefono.setText(em.getTelefono());
				jCBEmpRegEmpTipoEmpresa.setSelectedItem(em.getTipo());
				jTFEmpRegEmpDireccion.setText(em.getDireccion());
				jTFEmpRegEmpSitioWeb.setText(em.getSitioWeb());

				/* contacto */
				jTFEmpRegEmpContNomCompleto.setText(con.getNombreCompleto());
				jTFEmpRegEmpContCorreo.setText(con.getCorreo());
				jTFEmpRegEmpContCargoEmpresa.setText(con.getCargoEmpresa());
				jTFEmpRegEmpContTelefono.setText(con.getTelefono());

			} else {
				JOptionPane.showMessageDialog(null, "La empresa con el NIT: " + nit + " no se encontro");
			}
		}
	} catch (Exception e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}

	}// GEN-LAST:event_jBEmpEdiEmpCargarInformacionEditarActionPerformed

	private void jBEmpEdiEmpEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpEdiEmpEditarActionPerformed
		
		if (jTFEmpRegEmpNIT.getText().isEmpty() || jCBEmpRegEmpSectorLaboral.getSelectedIndex() == 0
				|| jCBEmpRegEmpCiudad.getSelectedIndex() == 0 || jCBEmpRegEmpDeportamento.getSelectedIndex() == 0
				||jCBEmpRegEmpPais.getSelectedIndex() == 0
				|| jTFEmpRegEmpRazonSocial.getText().isEmpty() || jTFEmpRegEmpTelefono.getText().isEmpty()
				|| jCBEmpRegEmpTipoEmpresa.getSelectedIndex() == 0 || jTFEmpRegEmpDireccion.getText().isEmpty()
				|| jTFEmpRegEmpSitioWeb.getText().isEmpty()
				||jTFEmpRegEmpContNomCompleto.getText().isEmpty()
				||jTFEmpRegEmpContCorreo.getText().isEmpty()
				||jTFEmpRegEmpContCargoEmpresa.getText().isEmpty()
				||jTFEmpRegEmpContTelefono.getText().isEmpty()
				) {
			JOptionPane.showMessageDialog(null, "Asegurese de ingresar todos los datos");
		} else {
			
			
       jTPEmpPestaniasInfEmpresas.setEnabledAt(0, true);
		jTPEmpPestaniasInfEmpresas.setSelectedIndex(0);
		jBEmpEdiEmpEditar.setEnabled(false);
		jBEmpRegEmpContRegistrar.setEnabled(true);

			try {
				String nit = jTFEmpRegEmpNIT.getText();
				SectorLaboral sec = (SectorLaboral) jCBEmpRegEmpSectorLaboral.getSelectedItem();
				Ciudad ciudad = (Ciudad) jCBEmpRegEmpCiudad.getSelectedItem();
				Departamento dep = (Departamento) jCBEmpRegEmpDeportamento.getSelectedItem();
				Pais pai = (Pais) jCBEmpRegEmpPais.getSelectedItem();
				String razonSocial = jTFEmpRegEmpRazonSocial.getText();
				String tel = jTFEmpRegEmpTelefono.getText();
				TipoEmpresa tipo = (TipoEmpresa) jCBEmpRegEmpTipoEmpresa.getSelectedItem();
				String sitioWeb = jTFEmpRegEmpSitioWeb.getText();
				String dirEmp = jTFEmpRegEmpDireccion.getText();
				Empresa empresa = new Empresa(nit,sec,ciudad,dep,pai,razonSocial,tel,tipo,dirEmp,sitioWeb);

				controlador.editarEmpresa(empresa);

				// contacto
				String nom = jTFEmpRegEmpContNomCompleto.getText();
				String email = jTFEmpRegEmpContCorreo.getText();
				String cargo = jTFEmpRegEmpContCargoEmpresa.getText();
				String telef = jTFEmpRegEmpContTelefono.getText();
				Contacto con = new Contacto(empresa, nom, email, cargo, telef);
				
				controlador.editarContacto(con);
				JOptionPane.showMessageDialog(null, "se editaron los datos");
				limpiarCampos();
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}// GEN-LAST:event_jBEmpEdiEmpEditarActionPerformed

	private void jBEmpRegOfeRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpRegOfeRegistrarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpRegOfeRegistrarActionPerformed

	private void jBEmpCerOfeActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpCerOfeActualizarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpCerOfeActualizarActionPerformed

	private void jBEmpCerOfeCerrarOfertaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpCerOfeCerrarOfertaActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpCerOfeCerrarOfertaActionPerformed

	private void jBEmpAplOfeVerDatosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpAplOfeVerDatosActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpAplOfeVerDatosActionPerformed

	private void jBEmpAplOfeAplicarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpAplOfeAplicarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpAplOfeAplicarActionPerformed

	private void jBEmpGesAreIntCrearActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpGesAreIntCrearActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpGesAreIntCrearActionPerformed

	private void jBEmpGesAreIntEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBEmpGesAreIntEditarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jBEmpGesAreIntEditarActionPerformed

	private void jBCerrarSesionConEmpActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCerrarSesionConEmpActionPerformed
		Login venL = new Login();
		venL.setVisible(true);
		this.setVisible(false);
	}// GEN-LAST:event_jBCerrarSesionConEmpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLoginLogo;
    private javax.swing.JButton jBCerrarSesionConEmp;
    private javax.swing.JButton jBEmpAplOfeAplicar;
    private javax.swing.JButton jBEmpAplOfeVerDatos;
    private javax.swing.JButton jBEmpCerOfeActualizar;
    private javax.swing.JButton jBEmpCerOfeCerrarOferta;
    private javax.swing.JButton jBEmpEdiEmpCargarInformacionEditar;
    private javax.swing.JButton jBEmpEdiEmpEditar;
    private javax.swing.JButton jBEmpGesAreIntCrear;
    private javax.swing.JButton jBEmpGesAreIntEliminar;
    private javax.swing.JButton jBEmpRegEmpContAtras;
    private javax.swing.JButton jBEmpRegEmpContRegistrar;
    private javax.swing.JButton jBEmpRegEmpSiguiente;
    private javax.swing.JButton jBEmpRegOfeRegistrar;
    private javax.swing.JComboBox jCBEmpAplOfeAreaInteres;
    private javax.swing.JComboBox jCBEmpRegEmpCiudad;
    private javax.swing.JComboBox jCBEmpRegEmpDeportamento;
    private javax.swing.JComboBox jCBEmpRegEmpPais;
    private javax.swing.JComboBox jCBEmpRegEmpSectorLaboral;
    private javax.swing.JComboBox jCBEmpRegEmpTipoEmpresa;
    private javax.swing.JComboBox jCBEmpRegOfeAreaConocimiento;
    private com.toedter.calendar.JDateChooser jDCEmpRegOfeFechaGrado;
    private javax.swing.JLabel jLEmpAplOfeAreaInteres;
    private javax.swing.JLabel jLEmpAplOfeOfertas;
    private javax.swing.JLabel jLEmpCerOfeOferta;
    private javax.swing.JLabel jLEmpEdiEmpNIT;
    private javax.swing.JLabel jLEmpGesAreIntNombreAreaInteres;
    private javax.swing.JLabel jLEmpRegEmpCiudad;
    private javax.swing.JLabel jLEmpRegEmpContCargoEmpresa;
    private javax.swing.JLabel jLEmpRegEmpContCorreo;
    private javax.swing.JLabel jLEmpRegEmpContNomCompleto;
    private javax.swing.JLabel jLEmpRegEmpContTelefono;
    private javax.swing.JLabel jLEmpRegEmpDepartamento;
    private javax.swing.JLabel jLEmpRegEmpDireccion;
    private javax.swing.JLabel jLEmpRegEmpNIT;
    private javax.swing.JLabel jLEmpRegEmpPais;
    private javax.swing.JLabel jLEmpRegEmpRazonSocial;
    private javax.swing.JLabel jLEmpRegEmpSectorLaboral;
    private javax.swing.JLabel jLEmpRegEmpSitioWeb;
    private javax.swing.JLabel jLEmpRegEmpTelefono;
    private javax.swing.JLabel jLEmpRegEmpTipoEmpresa;
    private javax.swing.JLabel jLEmpRegOfeAreaConocimiento;
    private javax.swing.JLabel jLEmpRegOfeCargoOfrecer;
    private javax.swing.JLabel jLEmpRegOfeCiudadOferta;
    private javax.swing.JLabel jLEmpRegOfeDescripcionOferta;
    private javax.swing.JLabel jLEmpRegOfeFechaGrado;
    private javax.swing.JLabel jLEmpRegOfeRequerimentosOferta;
    private javax.swing.JLabel jLEmpRegOfeResumen;
    private javax.swing.JLabel jLEmpRegOfeSalario;
    private javax.swing.JLabel jLEmpSistemaDeInformacionDeEgresados;
    private javax.swing.JLabel jLEmpSistemaDeInformacionDeEgresados1;
    private javax.swing.JPanel jPEmpAplicarOferta;
    private javax.swing.JPanel jPEmpBolsaEmpleo;
    private javax.swing.JPanel jPEmpCerrarOferta;
    private javax.swing.JPanel jPEmpEditarEmpresa;
    private javax.swing.JPanel jPEmpGestionAreaInteres;
    private javax.swing.JPanel jPEmpInfEmpresas;
    private javax.swing.JPanel jPEmpInfParametricas;
    private javax.swing.JPanel jPEmpRegistroEmpresasDatoContacto;
    private javax.swing.JPanel jPEmpRegistroEmpresasDatoEmpresa;
    private javax.swing.JPanel jPEmpRegistroOferta;
    private javax.swing.JPanel jPPrincipalC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTAEmpAplOfeOfertas;
    private javax.swing.JTextArea jTAEmpCerOfeOferta;
    private javax.swing.JTextArea jTAEmpListarAreInteres;
    private javax.swing.JTextArea jTAEmpRegOfeDescripcionOferta;
    private javax.swing.JTextArea jTAEmpRegOfeResumen;
    private javax.swing.JTextField jTFEmpEdiEmpNIT;
    private javax.swing.JTextField jTFEmpGesAreIntNombreAreaInteres;
    private javax.swing.JTextField jTFEmpRegEmpContCargoEmpresa;
    private javax.swing.JTextField jTFEmpRegEmpContCorreo;
    private javax.swing.JTextField jTFEmpRegEmpContNomCompleto;
    private javax.swing.JTextField jTFEmpRegEmpContTelefono;
    private javax.swing.JTextField jTFEmpRegEmpDireccion;
    private javax.swing.JTextField jTFEmpRegEmpNIT;
    private javax.swing.JTextField jTFEmpRegEmpRazonSocial;
    private javax.swing.JTextField jTFEmpRegEmpSitioWeb;
    private javax.swing.JTextField jTFEmpRegEmpTelefono;
    private javax.swing.JTextField jTFEmpRegOfeCargoOfrecer;
    private javax.swing.JTextField jTFEmpRegOfeCiudadOferta;
    private javax.swing.JTextField jTFEmpRegOfeRequerimentosOferta;
    private javax.swing.JTextField jTFEmpRegOfeSalario;
    private javax.swing.JTabbedPane jTPEAMPestaniasPrincipales;
    private javax.swing.JTabbedPane jTPEmpPestaniasBolsaEmpleo;
    private javax.swing.JTabbedPane jTPEmpPestaniasInfEmpresas;
    private javax.swing.JTabbedPane jTPEmpPestaniasInfParametrica;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

	
	private void listarSectorLaboral() {
		try {
			jCBEmpRegEmpSectorLaboral.removeAllItems();
			jCBEmpRegEmpSectorLaboral.addItem("Seleccione una Sector");
			List<SectorLaboral> lista = controlador.listarSectorLaboral();
			for (int i = 0; i < lista.size(); i++) {
				jCBEmpRegEmpSectorLaboral.addItem(lista.get(i));

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	private void listarCiudades() {
		try {
			jCBEmpRegEmpCiudad.removeAllItems();
			jCBEmpRegEmpCiudad.addItem("Seleccione una Ciudad");
			List<Ciudad> lista = controlador.listarCiudades();
			for (int i = 0; i < lista.size(); i++) {
				jCBEmpRegEmpCiudad.addItem(lista.get(i));

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	private void listarDepartamentos() {
		try {
			jCBEmpRegEmpDeportamento.removeAllItems();
			jCBEmpRegEmpDeportamento.addItem("Seleccione un Departamento");
			List<Departamento> lista = controlador.listarDepartamentos();
			for (int i = 0; i < lista.size(); i++) {

				jCBEmpRegEmpDeportamento.addItem(lista.get(i));

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	private void listarPaises() {
		try {
			jCBEmpRegEmpPais.removeAllItems();
			jCBEmpRegEmpPais.addItem("Seleccione un Pais");
			List<Pais> lista = controlador.listarPaises();
			for (int i = 0; i < lista.size(); i++) {
				jCBEmpRegEmpPais.addItem(lista.get(i));

			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}
	public void limpiarCampos(){
		jTFEmpEdiEmpNIT.setText(null);
		jTFEmpGesAreIntNombreAreaInteres.setText(null);
		jTFEmpRegEmpContCargoEmpresa.setText(null);
		jTFEmpRegEmpContCorreo.setText(null);
    	jTFEmpRegEmpContNomCompleto.setText(null);
    	jTFEmpRegEmpContTelefono.setText(null);
    	jTFEmpRegEmpRazonSocial.setText(null);
    	jTFEmpRegEmpSitioWeb.setText(null);
    	jTFEmpRegEmpTelefono.setText(null);
        jCBEmpAplOfeAreaInteres.setSelectedIndex(0);
        jCBEmpRegEmpCiudad.setSelectedIndex(0);
        jCBEmpRegEmpDeportamento.setSelectedIndex(0);
        jCBEmpRegEmpPais.setSelectedIndex(0);
        jCBEmpRegEmpSectorLaboral.setSelectedIndex(0);
        jCBEmpRegEmpTipoEmpresa.setSelectedIndex(0);
        jCBEmpRegOfeAreaConocimiento.setSelectedIndex(0);
    }
	
}
